# Generated by Django 5.0.14 on 2026-05-14 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intelligence", "0005_rejectionrecord_corrections"),
        ("public_core", "0043_plan_options_field"),
        ("tenants", "0015_tenantbusinessprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=128)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("attestation", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("confirmation_number", models.CharField(blank=True, max_length=128)),
                ("screenshot_path", models.CharField(blank=True, max_length=512)),
                ("error_class", models.CharField(blank=True, max_length=128)),
                ("error_message", models.TextField(blank=True)),
                ("traceback_truncated", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filing_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filing_jobs",
                        to="intelligence.filingstatusrecord",
                    ),
                ),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_jobs",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filing_jobs",
                        to="tenants.clientworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "filing_automation_filing_job",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="filing_auto_tenant__f60f93_idx",
                    ),
                    models.Index(
                        fields=["plan_snapshot", "status"],
                        name="filing_auto_plan_sn_8d277d_idx",
                    ),
                ],
            },
        ),
    ]
