# Generated by Django 5.0.14 on 2026-04-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_ingest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jurisdiction", models.CharField(max_length=8)),
                ("district_code", models.CharField(max_length=16)),
                ("source_file", models.TextField()),
                ("requirements", models.JSONField(default=dict)),
                ("preferences", models.JSONField(default=dict)),
                ("plugging_chart", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("jurisdiction", "district_code")},
            },
        ),
        migrations.CreateModel(
            name="CountyOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_name", models.CharField(max_length=128)),
                ("requirements", models.JSONField(default=dict)),
                ("preferences", models.JSONField(default=dict)),
                ("county_procedures", models.JSONField(default=dict)),
                ("formation_data", models.JSONField(default=dict)),
                (
                    "district_overlay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counties",
                        to="policy_ingest.districtoverlay",
                    ),
                ),
            ],
            options={
                "unique_together": {("district_overlay", "county_name")},
            },
        ),
    ]
