# Generated by Django 5.0.14 on 2026-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_ingest", "0002_districtoverlay_countyoverlay"),
    ]

    operations = [
        migrations.AddField(
            model_name="countyoverlay",
            name="notes",
            field=models.JSONField(default=list),
        ),
    ]
