# Generated by Django 5.0.14 on 2026-05-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0004_portalcredential_key_salt"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionrecord",
            name="accepted_corrections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="User-accepted corrections. Each entry: {issue_index, field_name, applied_value, accepted_at}",
            ),
        ),
        migrations.AddField(
            model_name="rejectionrecord",
            name="correction_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("partial", "Partial"),
                    ("all_applied", "All Applied"),
                ],
                db_index=True,
                default="none",
                max_length=20,
            ),
        ),
    ]
