# Generated by Django 5.0.14 on 2026-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0005_rejectionrecord_corrections"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalcredential",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="True when this credential is paired with a sandbox / test account. Live RRC submissions only fire when settings.RRC_LIVE_SUBMIT_ENABLED is True AND is_test is False — i.e. production credentials submit for real, test credentials always save as draft.",
            ),
        ),
    ]
