# Generated by Django 5.0.14 on 2026-06-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0006_portalcredential_is_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalcredential",
            name="auth_state",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("needs_reauth", "Needs Re-auth"),
                    ("locked", "Locked"),
                ],
                db_index=True,
                default="ok",
                help_text="Current authentication circuit-breaker state for this credential.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="portalcredential",
            name="consecutive_login_failures",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of consecutive login failures since last success.",
            ),
        ),
        migrations.AddField(
            model_name="portalcredential",
            name="last_login_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error message from the most recent login failure (truncated to 1000 chars).",
            ),
        ),
        migrations.AddField(
            model_name="portalcredential",
            name="last_login_failure_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent login failure.",
                null=True,
            ),
        ),
    ]
