# Generated by Django 5.0.14 on 2026-06-21 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0007_portalcredential_auth_state_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="portalcredential",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="portalcredential",
            name="is_default_for_automation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="portalcredential",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="portalcredential",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant_id", "agency"),
                name="uniq_cred_user_tenant_agency",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalcredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default_for_automation", True)),
                fields=("tenant_id", "agency"),
                name="uniq_one_automation_default_per_tenant_agency",
            ),
        ),
    ]
