# Generated by Django 5.0.14 on 2026-04-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0041_manual_wbd"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="manualwbd",
            new_name="public_core_api14_017f92_idx",
            old_name="public_core_api14_te_diagty_idx",
        ),
        migrations.RenameIndex(
            model_name="manualwbd",
            new_name="public_core_tenant__d7a0e6_idx",
            old_name="public_core_tenant_id_mwbd_idx",
        ),
        migrations.AddField(
            model_name="historicalw3wizardsession",
            name="event_compliance_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-event regulatory compliance flags from event_compliance_checker",
            ),
        ),
        migrations.AddField(
            model_name="w3wizardsession",
            name="event_compliance_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-event regulatory compliance flags from event_compliance_checker",
            ),
        ),
        migrations.AlterField(
            model_name="historicalw3wizardsession",
            name="current_step",
            field=models.IntegerField(
                default=1,
                help_text="1=upload, 2=verify-plan, 3=review, 4=reconciliation, 5=justification, 6=as-plugged-diagram, 7=generate",
            ),
        ),
        migrations.AlterField(
            model_name="historicalw3wizardsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("uploading", "uploading"),
                    ("importing_plan", "importing_plan"),
                    ("plan_imported", "plan_imported"),
                    ("plan_verified", "plan_verified"),
                    ("parsing", "parsing"),
                    ("parsed", "parsed"),
                    ("reconciled", "reconciled"),
                    ("justifying", "justifying"),
                    ("ready", "ready"),
                    ("generating", "generating"),
                    ("completed", "completed"),
                    ("abandoned", "abandoned"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="w3wizardsession",
            name="current_step",
            field=models.IntegerField(
                default=1,
                help_text="1=upload, 2=verify-plan, 3=review, 4=reconciliation, 5=justification, 6=as-plugged-diagram, 7=generate",
            ),
        ),
        migrations.AlterField(
            model_name="w3wizardsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("uploading", "uploading"),
                    ("importing_plan", "importing_plan"),
                    ("plan_imported", "plan_imported"),
                    ("plan_verified", "plan_verified"),
                    ("parsing", "parsing"),
                    ("parsed", "parsed"),
                    ("reconciled", "reconciled"),
                    ("justifying", "justifying"),
                    ("ready", "ready"),
                    ("generating", "generating"),
                    ("completed", "completed"),
                    ("abandoned", "abandoned"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
    ]
