# Generated by Django 5.0.14 on 2026-05-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0042_add_event_compliance_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalw3wizardsession",
            name="plan_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Operator plan generation preferences (combine_nearby_plugs, combine_threshold_ft, surface_plug_bottom_ft)",
            ),
        ),
        migrations.AddField(
            model_name="w3wizardsession",
            name="plan_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Operator plan generation preferences (combine_nearby_plugs, combine_threshold_ft, surface_plug_bottom_ft)",
            ),
        ),
    ]
