# Generated by Django 5.0.14 on 2026-06-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0043_plan_options_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_number", models.CharField(db_index=True, max_length=16)),
                ("href", models.TextField()),
                ("filename", models.CharField(max_length=255)),
                ("local_path", models.TextField(blank=True)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("kind", models.CharField(blank=True, max_length=64)),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("error", "Error"),
                            ("unsupported", "Unsupported"),
                            ("skipped_directional", "Skipped — Directional Survey"),
                            ("no_forms", "No Forms Found"),
                            ("quota_exceeded", "Quota Exceeded"),
                            ("failed", "Failed (worker killed)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("source_type", models.CharField(default="rrc", max_length=16)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extracted_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieved_documents",
                        to="public_core.extracteddocument",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieved_documents",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_retrieved_documents",
                "indexes": [
                    models.Index(
                        fields=["api_number", "index_status"],
                        name="public_core_api_num_d2b89f_idx",
                    ),
                    models.Index(
                        fields=["downloaded_at"], name="public_core_downloa_5713d4_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="retrieveddocument",
            constraint=models.UniqueConstraint(
                fields=("api_number", "href"), name="uniq_retrieved_doc_api_href"
            ),
        ),
    ]
