# Generated by Django 5.0.14 on 2026-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0044_retrieved_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchsession",
            name="api_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
