# Generated by Django 5.0.14 on 2026-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Change Notification.tenant_id from UUIDField to a BigIntegerField-backed
    custom FlexTenantIdField.

    The Tenant.id PK is an auto-integer (BigAutoField), not a UUID.
    Storing tenant_id as bigint means notification.tenant_id == tenant.id
    works correctly as an integer comparison.

    A custom get_prep_value on the field handles UUID inputs by folding them
    into 63-bit space (for isolation-test use cases).

    Uses a DROP/ADD approach to avoid the UUID->bigint cast error on non-empty
    tables.
    """

    dependencies = [
        ("tenants", "0011_notification_beat"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenants_notification
                    DROP COLUMN IF EXISTS tenant_id;
                ALTER TABLE tenants_notification
                    ADD COLUMN tenant_id bigint NOT NULL DEFAULT 0;
                CREATE INDEX IF NOT EXISTS tenants_notif_tenant_id_bigint_idx
                    ON tenants_notification (tenant_id);
            """,
            reverse_sql="""
                ALTER TABLE tenants_notification
                    DROP COLUMN IF EXISTS tenant_id;
                ALTER TABLE tenants_notification
                    ADD COLUMN tenant_id uuid NOT NULL
                    DEFAULT '00000000-0000-0000-0000-000000000000';
            """,
        ),
        migrations.AlterField(
            model_name="notification",
            name="tenant_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
