# Generated by Django 5.0.14 on 2026-05-14 01:24

import apps.tenants.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_fix_tenant_id_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="tenant_id",
            field=apps.tenants.models.FlexTenantIdField(db_index=True),
        ),
    ]
